[package]
name = "gpui-lucide"
description = "Lucide icons for GPUI"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gpui.workspace = true

[build-dependencies]
heck = "0.5"

[dev-dependencies]
